# Generated by Django 5.0.7 on 2024-07-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.ManyToManyField(null=True, to='blog.tag'),
        ),
    ]
